python nni_tuning.py -e=country_classification -v=classic -n=minmax -m=GraphSAGE
python nni_tuning.py -e=continent_classification -v=classic -n=minmax -m=GraphSAGE
python nni_tuning.py -e=rir_classification -v=classic -n=minmax -m=GraphSAGE
python nni_tuning.py -e=business_classification -v=classic -n=minmax -m=GraphSAGE
python nni_tuning.py -e=link_classification -v=default -n=minmax -m=GraphSAGE
python nni_tuning.py -e=country_classification -v=default -n=minmax -m=GraphSAGE
python nni_tuning.py -e=continent_classification -v=default -n=minmax -m=GraphSAGE
python nni_tuning.py -e=rir_classification -v=default -n=minmax -m=GraphSAGE
python nni_tuning.py -e=business_classification -v=default -n=minmax -m=GraphSAGE
python nni_tuning.py -e=country_classification -v=classic -n=minmax -m=GCN
python nni_tuning.py -e=continent_classification -v=classic -n=minmax -m=GCN
python nni_tuning.py -e=rir_classification -v=classic -n=minmax -m=GCN
python nni_tuning.py -e=business_classification -v=classic -n=minmax -m=GCN
python nni_tuning.py -e=link_classification -v=default -n=minmax -m=GCN
python nni_tuning.py -e=country_classification -v=default -n=minmax -m=GCN
python nni_tuning.py -e=continent_classification -v=default -n=minmax -m=GCN
python nni_tuning.py -e=rir_classification -v=default -n=minmax -m=GCN
python nni_tuning.py -e=business_classification -v=default -n=minmax -m=GCN
python nni_tuning.py -e=country_classification -v=classic -n=minmax -m=GAT
python nni_tuning.py -e=continent_classification -v=classic -n=minmax -m=GAT
python nni_tuning.py -e=rir_classification -v=classic -n=minmax -m=GAT
python nni_tuning.py -e=business_classification -v=classic -n=minmax -m=GAT
python nni_tuning.py -e=link_classification -v=default -n=minmax -m=GAT
python nni_tuning.py -e=country_classification -v=default -n=minmax -m=GAT
python nni_tuning.py -e=continent_classification -v=default -n=minmax -m=GAT
python nni_tuning.py -e=rir_classification -v=default -n=minmax -m=GAT
python nni_tuning.py -e=business_classification -v=default -n=minmax -m=GAT
python nni_tuning.py -e=country_classification -v=classic -n=minmax -m=GIN
python nni_tuning.py -e=continent_classification -v=classic -n=minmax -m=GIN
python nni_tuning.py -e=rir_classification -v=classic -n=minmax -m=GIN
python nni_tuning.py -e=business_classification -v=classic -n=minmax -m=GIN
python nni_tuning.py -e=link_classification -v=default -n=minmax -m=GIN
python nni_tuning.py -e=country_classification -v=default -n=minmax -m=GIN
python nni_tuning.py -e=continent_classification -v=default -n=minmax -m=GIN
python nni_tuning.py -e=rir_classification -v=default -n=minmax -m=GIN
python nni_tuning.py -e=business_classification -v=default -n=minmax -m=GIN